# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d3f424503a0f57b1d7f2850d35dd1b2e4032431e97f46396cbbc164f1f47301b5b880e2ef2c9a74da3f7e73efd0d56c9fd5f39de7f252230f4cf8bd486350a

test:
  secret_key_base: 8af49a609624202c29d055185fc370bf90cc4d4512c0c42b02fc3da9b9526a642c04ce06521445c0610b2e1cd5abb06460c4b792d78820d1c7d9f0ed0f6f3717

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
